### ISSUE TITLE
1.15.2 crash

### ISSUE THREAD

**Issue by Zenith-One** [Rohzek/SimpleDivingGear#10]
In my survival world, I was putting on my air tank (replacing my diamond chestplate in case that helps somehow?) and the game crashed with the following exception: https://pastebin.com/YBJMuLUz

The mod version is 4.0.1

Based on the line in the code which the exception points to, it seems like it's an issue with casting a config value to a float, so I feel obligated to point out that I haven't touched the SimpleDivingGear configs at all, it's 100% default.

**Comment by ghost** [comment]
I've got the same crash: https://pastebin.com/4VNKz6k5

Minecraft 1.15.2
Forge 31.2.41
Simple Diving Gear 4.0.1
