### ISSUE TITLE
Server Crash (MC 1.14.4, Forge 28.0.55)

### ISSUE THREAD

**Issue by General-Radek** [Rohzek/SimpleDivingGear#6]
When I launch my server with this mod installed it crashes. Without the mod it goes ok.

Here are the log and crash report:
[latest.log](https://github.com/Rohzek/SimpleDivingGear/files/3538154/latest.log)
[crash-2019-08-25_16.03.03-server.txt](https://github.com/Rohzek/SimpleDivingGear/files/3538156/crash-2019-08-25_16.03.03-server.txt)

**Comment by Rohzek** [comment]
I'm not sure what my mod has to do with the issue, but according to the log, both instances of the crash being mentioned originates with another mod:

Lines 385-398
`[25авг.2019 16:03:03.712] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
...
	at lykrast.mysticalwildlife.common.init.ModEntities.makeSpawns(ModEntities.java:102)
	at lykrast.mysticalwildlife.core.MysticalWildlife.setupCommon(MysticalWildlife.java:36)
...`

Lines 433-443
`[25авг.2019 16:03:03.718] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid mysticalwildlife
java.util.ConcurrentModificationException: null
...
	at lykrast.mysticalwildlife.common.init.ModEntities.makeSpawns(ModEntities.java:102) ~[?:?]
	at lykrast.mysticalwildlife.core.MysticalWildlife.setupCommon(MysticalWildlife.java:36) ~[?:?]
...`

If you want to drop the debug.log here, too, I'll try to look into it farther, but as it is now, I don't know how to help. Might want to try at that mod's bug tracker, too.
